version: '3.3'

networks:
  # net:
  #   driver: overlay
  #   attachable: true
  traefik-public:
    external: true

services:
  dash:
    image: tethysts/tethys-es-rivers-dash:1.8
    networks:
      # - net
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.labels.function == web_server
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.es-dash-http.rule=Host(`test1.nzrivers.xyz`)
        - traefik.http.routers.es-dash-http.entrypoints=http
        - traefik.http.routers.es-dash-http.middlewares=https-redirect
        - traefik.http.routers.es-dash-https.rule=Host(`test1.nzrivers.xyz`)
        - traefik.http.routers.es-dash-https.entrypoints=https
        - traefik.http.routers.es-dash-https.tls=true
        # - traefik.http.routers.es-dash-https.tls.certresolver=le
        - traefik.http.services.es-dash.loadbalancer.server.port=80
