version: '3'

services:
  # db:
  #   image: mongo:4.2-bionic
  #   command: --wiredTigerJournalCompressor zstd --wiredTigerCollectionBlockCompressor zstd
  #   # ports:
  #   #   - "27017:27017"
  # db-init:
  #   image: tethysts/tethys-db-initialize:dev
  #   volumes:
  #       - /media/sdb1/Projects/git/tethys/tethys-extraction-es-hilltop/plots/parameters.yml:/parameters.yml
  #   depends_on:
  #     - "db"
  # web-service:
  #   image: tethysts/tethys-web-service:dev
  #   depends_on:
  #     - "db"
    # ports:
    #   - "8080:80"
  es-rivers-dash:
    image: tethysts/tethys-es-rivers-dash:1.4
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    # depends_on:
    #   - "web-service"
    ports:
      - "8080:80"
