remotes:
  - bucket: es-hilltop
    public_url: https://b2.tethys-ts.xyz/file
    version: 4
  - bucket: nz-water-use
    public_url: https://b2.tethys-ts.xyz/file
    version: 4
# cache_path: /cache
cache_path: /media/nvme1/data/cache
